### PR TITLE
Implement bookmarks

### PR DESCRIPTION
**Pull request by annavik**
### Summary
- Make it possible to mark guidelines as bookmarked (for now we only keep this info in browser, no login required)
- Show bookmarked guidelines in a separate list (we introduce a tab bar for this)
- Show notification when bookmarks are updated

Let me know what you think, design is just a suggestion!

### Screenshot
Screenshot 2023-12-28 at 17 12 21

### CODE REVIEW

**Comment by thibaudcolas** [comment]
This looks great to me! If you want an example of a use case, here is me doing my bookmarking: [My rating of web sustainability guidelines](https://thib.me/my-rating-of-web-sustainability-guidelines) so I know which guidelines / SCs to get back to in the future.

As a "next" improvement on top of this, what would be killer for me is to be able to "export" this list of bookmarks – make a long URL with all the bookmarked items’ identifiers in there, so I can send to someone and say "here’s the guidelines I would recommend you look at". Then on their site it wouldn’t arrive as a bookmark, just a filter.

**Comment by annavik** [comment]
> This looks great to me! If you want an example of a use case, here is me doing my bookmarking: [My rating of web sustainability guidelines](https://thib.me/my-rating-of-web-sustainability-guidelines) so I know which guidelines / SCs to get back to in the future.
> 
> As a "next" improvement on top of this, what would be killer for me is to be able to "export" this list of bookmarks – make a long URL with all the bookmarked items’ identifiers in there, so I can send to someone and say "here’s the guidelines I would recommend you look at". Then on their site it wouldn’t arrive as a bookmark, just a filter.

Thanks again for the comments @thibaudcolas! Your rating system makes me think maybe setting a status, rather than just mark as bookmarked, could be useful? But yes, maybe for future.

Love the idea with making it possible to also share the bookmarks! I wonder how long a simple URL solution would hold, because I'm thinking next step then would probably be to have shared collections in teams? But that would require we introduce a BE service.

**Review by c0ldbear — APPROVED** [review]
Awesome! :D Great work

**Comment by annavik** [comment]
Merging this as is for now, but created a follow up issue for discussion around sharing bookmarks: https://github.com/annavik/websustainability/issues/18

**Pull request merged**
