### PR TITLE
Guideline details

### PR DESCRIPTION
**Pull request by annavik**
New attempt to include success criteria, this time using a detail view approach. Let me know what you think! Preview deploy is now working, check it out 👇

Except for making success criteria visible, we also make it possible to link to a specific guideline (and also to a success criterion within a guideline).

### Summary of changes:
- Add routing to app
- New route for guideline details: `/:id/:slug?`
- New view for guideline details, including success criteria
- Update list view cards to link to details
- Skip buttons in list view cards, since cards are now links
- Add success criteria anchor links

### Comments:
- Success criteria items also have anchor links. However, the current API does not return any success criterion ID:s. Current ID:s are just created from index, so perhaps not a very stable solution?
- If we like this details view approach, I will also add some list view scroll restoration (so that scroll position is kept if you go from list view -> detail view -> back to list view).

### Screenshots:
Screenshot 2024-01-21 at 17 51 05
Screenshot 2024-01-21 at 17 51 09

### CODE REVIEW

**Comment by c0ldbear** [comment]
> Success criteria items also have anchor links. However, the current API does not return any success criterion ID:s. Current ID:s are just created from index, so perhaps not a very stable solution?

I think it's quite easy to get the IDs and/or anchor-links to the success critera on w3c if we want it, but would that really be necessary? Since we will have the success critera here too now, then maybe a link is not really needed? Or what do you think?

**Comment by c0ldbear** [comment]
> If we like this details view approach, I will also add some list view scroll restoration (so that scroll position is kept if you go from list view -> detail view -> back to list view).

In general, I like the approach! But I noticed that I first that it was a bit difficult to understand that I was moved to a new view, and I instinctively tried clicking outside of the "card"/"view" to go back. What do you think about that approach, make it a "card" that is on top and when you press outside of it you can see what's behind it?

**Comment by annavik** [comment]
> > Success criteria items also have anchor links. However, the current API does not return any success criterion ID:s. Current ID:s are just created from index, so perhaps not a very stable solution?
> 
> I think it's quite easy to get the IDs and/or anchor-links to the success critera on w3c if we want it, but would that really be necessary? Since we will have the success critera here too now, then maybe a link is not really needed? Or what do you think?

Sorry, I was a bit unclear! I ment the success criteria links we have on this site are just made up by index. For example the "3" in https://deploy-preview-21--websustainability.netlify.app/22/assess-and-research-visitor-needs#success-criterion-3.

This means if original guidelines would change the SC order, this link would suddenly link to a different SC. I would prefer to refer to a SC by a proper ID, but it's not possible atm.

**Comment by c0ldbear** [comment]
> > > Success criteria items also have anchor links. However, the current API does not return any success criterion ID:s. Current ID:s are just created from index, so perhaps not a very stable solution?
> > 
> > 
> > I think it's quite easy to get the IDs and/or anchor-links to the success critera on w3c if we want it, but would that really be necessary? Since we will have the success critera here too now, then maybe a link is not really needed? Or what do you think?
> 
> Sorry, I was a bit unclear! I ment the success criteria links we have on this site are just made up by index. For example the "3" in https://deploy-preview-21--websustainability.netlify.app/22/assess-and-research-visitor-needs#success-criterion-3.
> 
> This means if original guidelines would change the SC order, this link would suddenly link to a different SC. I would prefer to refer to a SC by a proper ID, but it's not possible atm.

Ah! Okey! :D I missunderstod! But maybe that's enough? Do we need a URL that is explaining itself? :D I mean, sure it would be nice though but is it hard to make? Or if we change our data, maybe it's easier?

**Comment by annavik** [comment]
> > If we like this details view approach, I will also add some list view scroll restoration (so that scroll position is kept if you go from list view -> detail view -> back to list view).
> 
> In general, I like the approach! But I noticed that I first that it was a bit difficult to understand that I was moved to a new view, and I instinctively tried clicking outside of the "card"/"view" to go back. What do you think about that approach, make it a "card" that is on top and when you press outside of it you can see what's behind it?

I like this idea Teddy! Let me just think about how to make it accessible, I think the linking is important here. Can we trigger a dialog on URL? Or I mean I know we can, but I want to double check the accessibility perspective here. Will get back to you!

**Comment by c0ldbear** [comment]
> > > > If we like this details view approach, I will also add some list view scroll restoration (so that scroll position is kept if you go from list view -> detail view -> back to list view).
> > > 
> > > 
> > > In general, I like the approach! But I noticed that I first that it was a bit difficult to understand that I was moved to a new view, and I instinctively tried clicking outside of the "card"/"view" to go back. What do you think about that approach, make it a "card" that is on top and when you press outside of it you can see what's behind it?
> > 
> > 
> > I like this idea Teddy! Let me just think about how to make it accessible, I think the linking is important here. Can we trigger a dialog on URL? Or I mean I know we can, but I want to double check the accessibility perspective here. Will get back to you!
> 
> A colleague suggested this. Modal when clicking, page when entering by URL: https://nextjs.org/docs/app/building-your-application/routing/parallel-routes
> 
> We are not using Next in this project, but the approach could perhaps be worth exploring...

Ah, I like it! Specifically the Modal 😄 But I think it's as it is now with the latest commits! Great work @annavik :)

**Pull request merged**
